USE [master]
GO
/****** Object:  Database [CrossesAndZeros]    Script Date: 10.03.2023 20:22:56 ******/
CREATE DATABASE [CrossesAndZeros]
 
GO
ALTER DATABASE [CrossesAndZeros] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET ARITHABORT OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CrossesAndZeros] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CrossesAndZeros] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CrossesAndZeros] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CrossesAndZeros] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CrossesAndZeros] SET  MULTI_USER 
GO
ALTER DATABASE [CrossesAndZeros] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CrossesAndZeros] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CrossesAndZeros] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CrossesAndZeros] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CrossesAndZeros] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CrossesAndZeros] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CrossesAndZeros] SET QUERY_STORE = OFF
GO
USE [CrossesAndZeros]
GO
/****** Object:  Table [dbo].[Games]    Script Date: 10.03.2023 20:22:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Games](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SquareStates] [nvarchar](50) NULL,
	[Description] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Games] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Games] ON 
GO
INSERT [dbo].[Games] ([Id], [SquareStates], [Description]) VALUES (1, N'111000000', N'gg')
GO
INSERT [dbo].[Games] ([Id], [SquareStates], [Description]) VALUES (2, N'000111000', N'22')
GO
INSERT [dbo].[Games] ([Id], [SquareStates], [Description]) VALUES (3, N'100100100', N'3')
GO
INSERT [dbo].[Games] ([Id], [SquareStates], [Description]) VALUES (6, N'100010001', N'ereg')
GO
SET IDENTITY_INSERT [dbo].[Games] OFF
GO
USE [master]
GO
ALTER DATABASE [CrossesAndZeros] SET  READ_WRITE 
GO
